config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  # Sidekiq Dashboard
  if Rails.env.production?
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      username == ENV['SIDEKIQ_USERNAME'] && password == ENV['SIDEKIQ_PASSWORD']
    end
  end
  mount Sidekiq::Web => '/sidekiq'

  # Devise routes
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks'
  }

  # Match a slug on the root route only if it has a corresponding Link.
  # Using the constraint causes invalid slugs to return 404 which is the
  # preferred behavior.
  get '/:slug', to: 'redirects#show', constraints: ActiveSlugConstraint.new

  resources :links, only: [:create]
  resources :dashboard, only: [:index]
  root 'pages#home'
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

# Controller for user dashboard routes
class DashboardController < SecureController
  def index
    @dashboard = DashboardPresenter.new
  end
end

app/views/dashboard/index.html.erb
<% page_title('Dashboard | URL Shortener') %>

<div class="my-6">
  <%= form_with(model: @dashboard.new_link, url: links_path) do |form| %>
    <div class="mb-3">
      <%= form.label :url, 'Enter a URL to shorten:', class: 'form-label' %>
      <%= form.text_field :url, class: 'form-input', placeholder: 'URL to shorten' %>
    </div>

    <div>
      <%= form.submit class: 'btn btn-blue' %>
    </div>
  <% end %>
</div>

<hr>

<div class="my-6">
  <h3 class="mb-2">Recent Links</h3>
  <ul>
    <% if @dashboard.recent_links.any? %>
      <% @dashboard.recent_links.each do |link| %>
        <li class="mb-5">
          <strong>Link ID: </strong>
          <%= link.id %>
          <br>

          <strong>Long URL: </strong>
          <%= link_to link.url, link.url, target: '_blank', rel: 'noopener' %>
          <br>

          <% if link.approved? %>
            <strong>Short URL: </strong>
            <%= link_to link.short_url, link.relative_short_url, target: '_blank', rel: 'noopener' %>
          <% end %>

          <div class="my-1">
            <span class="link-status-badge-<%= link.status.dasherize %>">
              <%= link.status.titleize %>
            </span>
          </div>
        </li>
      <% end %>
    <% else %>
      <li>No links to dispaly</li>
    <% end %>
  </ul>
</div>

app/views/dashboard/show.html.erb
<% page_title('Dashboard | URL Shortener') %>

<div class="mb-6">
  <h1>URLs are <span class="italic">TOO DAMN LONG!!!</span></h1>
</div>

<hr>

<div class="my-6">
  <%= form_with(model: @dashboard.new_link, url: links_path) do |form| %>
    <div class="mb-3">
      <%= form.label :url, 'Enter a URL to shorten:', class: 'form-label' %>
      <%= form.text_field :url, class: 'form-input', placeholder: 'URL to shorten' %>
    </div>

    <div>
      <%= form.submit class: 'btn btn-blue' %>
    </div>
  <% end %>
</div>

<hr>

<div class="my-6">
  <h3 class="mb-2">Recent Links</h3>
  <ul>
    <% if @dashboard.recent_links.any? %>
      <% @dashboard.recent_links.each do |link| %>
        <li class="mb-5">
          <strong>Link ID: </strong>
          <%= link.id %>
          <br>

          <strong>Long URL: </strong>
          <%= link_to link.url, link.url, target: '_blank', rel: 'noopener' %>
          <br>

          <% if link.approved? %>
            <strong>Short URL: </strong>
            <%= link_to link.short_url, link.relative_short_url, target: '_blank', rel: 'noopener' %>
          <% end %>

          <div class="my-1">
            <span class="link-status-badge-<%= link.status.dasherize %>">
              <%= link.status.titleize %>
            </span>
          </div>
        </li>
      <% end %>
    <% else %>
      <li>No links to dispaly</li>
    <% end %>
  </ul>
</div>