config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  # Sidekiq Dashboard
  if Rails.env.production?
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      username == ENV['SIDEKIQ_USERNAME'] && password == ENV['SIDEKIQ_PASSWORD']
    end
  end
  mount Sidekiq::Web => '/sidekiq'

  # Devise routes
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks'
  }

  # Match a slug on the root route only if it has a corresponding Link.
  # Using the constraint causes invalid slugs to return 404 which is the
  # preferred behavior.
  get '/:slug', to: 'redirects#show', constraints: ActiveSlugConstraint.new

  resources :links, only: [:create]
  resources :dashboard, only: [:index]
  root 'pages#home'
end

app/views/shared/navbar/_authenticated_navbar.html.erb
<nav class="navbar">
  <%=
    link_to dashboard_index_path do
      render 'shared/navbar/navbar_logo'
    end
  %>

  <div class="float-right">
    <%=
      link_to 'Sign Out', destroy_user_session_path,
              class: 'btn btn-inverted-blue',
              method: :delete
    %>
  </div>
</nav>

app/views/shared/navbar/_navbar.html.erb
<%=
  if current_user
    render 'shared/navbar/authenticated_navbar'
  else
    render 'shared/navbar/unauthenticated_navbar'
  end
%>

app/views/shared/navbar/_navbar_logo.html.erb
<div class="flex items-center flex-shrink-0 text-white mr-6">
  <span class="font-semibold text-xl tracking-tight">
    <%= unicode_icon(:diagonal_rectangles) %>
    SawFish
  </span>
</div>

app/views/shared/navbar/_unauthenticated_navbar.html.erb
<nav class="navbar">
  <%=
    link_to root_path do
      render 'shared/navbar/navbar_logo'
    end
  %>

  <div class="float-right">
    <%= link_to 'Sign In', new_user_session_path, class: 'btn btn-inverted-blue' %>
  </div>
</nav>